### ISSUE TITLE
Failure/Error: require "rails_helper"

### ISSUE THREAD

**Issue by dudyn5ky1** [vim-test/vim-test#524]
Hello,

I was using `vim-test` for quite some time already and it was working fine for my Rails projects. However, after the last update, I can't run tests (`:TestFile`) for ruby files anymore.

```
An error occurred while loading ./my_controller_spec.rb.
Failure/Error: require "rails_helper"

LoadError:
  cannot load such file -- rails_helper
# ./my_controller_spec.rb:1:in `require'
# ./my_controller_spec.rb:1:in `<top (required)>'
No examples found.


Finished in 0.00003 seconds (files took 0.08815 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

```

**Comment by dudyn5ky1** [comment]
Alright, it's a problem with startify changing working directory. 

https://github.com/mhinz/vim-startify/issues/387

Closing this issue.
