### ISSUE TITLE
TestNearest not escaping punctuation in test name correctly in jest/TypeScript tests

### ISSUE THREAD

**Issue by mackstann** [vim-test/vim-test#815]
### With vanilla config

I just updated vim-test and it's at commit c090bfd93919888bb0b86e1ab707bc6a3095097f. This issue has been occurring for me for probably a couple years at least.

My (jest & typescript) test file (`test/vimTestRepro.ts`):

```typescript
it('(runs this test)', async () => {
  expect(1).toEqual(1);
});
```

My .vimrc has all vim-test settings commented out, so it's the vanilla config.

Running `:TestNearest` within the above test results in the following output:

```
node_modules/.bin/jest --runTestsByPath -t '\(runs this test\)$' -- test/vimTestRepro.test.ts

Determining test suites to run...
Test Suites: 1 skipped, 0 of 1 total
Tests:       1 skipped, 1 total
Snapshots:   0 total
Time:        1.219 s
Ran all test suites within paths "test/vimTestRepro.test.ts".

Press ENTER or type command to continue
```

Strangely, if I run the above command directly in zsh (which is my login shell and should be used universally here AFAIK), it works:

```
% node_modules/.bin/jest --runTestsByPath -t '\(runs this test\)$' -- test/vimTestRepro.test.ts

Determining test suites to run...
 PASS  test/vimTestRepro.test.ts
  ✓ (runs this test) (2 ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.513 s, estimated 2 s
Ran all test suites within paths "test/vimTestRepro.test.ts".
```

If I _only_ have an opening parenthesis, I get this JavaScript Regex exception, which might hint at what is going wrong here:

```
node_modules/.bin/jest --runTestsByPath -t '\(runs this test$' -- test/vimTestRepro.test.ts

Determining test suites to run...
 FAIL  test/vimTestRepro.test.ts
  ● Test suite failed to run

    SyntaxError: Invalid regular expression: /\\(runs this test$/: Unterminated group
        at new RegExp (<anonymous>)

      at eventHandler (../node_modules/.pnpm/jest-circus@27.5.1/node_modules/jest-circus/build/eventHandler.js:305:33)
      at TestScheduler.scheduleTests (../node_modules/.pnpm/@jest+core@27.5.1_ts-node@10.5.0/node_modules/@jest/core/build/TestScheduler.js:333:13)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.39 s
Ran all test suites within paths "test/vimTestRepro.test.ts".

shell returned 1
```

### Alternate setup

With my usual config, I have the same problem but it looks a little different.

vimrc:
```
let test#strategy = 'vimterminal'
let test#typescript#jest#executable = 'pnpm run test --watchAll=false'
```

Result of `:TestNearest`:

```
> NODE_OPTIONS='--max-old-space-size=3072' jest --logHeapUsage --maxWorkers=50% "--watchAll=false" "--runTestsByPath" "-t" "\\\\(runs this test\\\\)$" "--" "test/vimTestRepro.test.ts"

Determining test suites to run...
Test Suites: 1 skipped, 0 of 1 total
Tests:       1 skipped, 1 total
Snapshots:   0 total
Time:        1.089 s
Ran all test suites within paths "test/vimTestRepro.test.ts".
```

If I run _that_ command directly in zsh, it also ends up skipping the test:

```
% NODE_OPTIONS='--max-old-space-size=3072' pnpm jest --logHeapUsage --maxWorkers=50% "--watchAll=false" "--runTestsByPath" "-t" "\\\\(runs this test\\\\)$" "--" "test/vimTestRepro.test.ts"

Determining test suites to run...
Test Suites: 1 skipped, 0 of 1 total
Tests:       1 skipped, 1 total
Snapshots:   0 total
Time:        1.613 s, estimated 2 s
Ran all test suites within paths "test/vimTestRepro.test.ts".
```

If I halve the number of backslashes, it works.

### Other punctuation

Square brackets exhibit the same problem. `$` and `.` and `*` seem to work fine.

**Comment by codeinabox** [comment]
Thank you for flagging this, I will look into this.

**Comment by codeinabox** [comment]
This is an interesting one as I am trying to recreate it, what version of jest are you using?
